### ISSUE TITLE
<non>interruptible cast colors coherency

### ISSUE THREAD

**Issue by Leiludallas** [lithammer/NeavUI#240]
Hi,

First of all, thank you for you great UI.

I used to track target castbars and nameplates castbars with some coloring coherency.
I personnaly use orange for interruptible casts and red for non-interruptible casts plus violet for a short time for successful interrupts (with the name of guy who cut). This if for all my castbars : nameplates, personnal, focus, assist and target castbars.

Currently, in your UI, we have red for all target castbars with border coloring for interruptible spells, and we have I think, grey, green and yellow colors for nameplate castbars with again 2 different borders colors.

I do think it'll be simplier and visualy better if we can use 2 castbar colors (maybe 3 for successful interrupts) on both nplates castbars and target (and personnal/focus/assist) castbars.

Sorry for my bad english.

All the best,
Leilu

**Comment by Grimsbain** [comment]
@lithammer How do you want to handle this? I was thinking we could consolidate all of the castbar color options into one section in the config and then match the colors to the default blizzard colors. Then if someone wanted to use custom colors they only have to make the change once instead of for every unit.

We can also easily make the castbar show interrupted. It only takes a single line to enable it and then a few more to handle the coloring. 
![wowscrnshot_080818_235624](https://user-images.githubusercontent.com/140057/43881115-5df7eff4-9b68-11e8-8cc1-27325b8c3a11.jpg)

**Comment by lithammer** [comment]
>I was thinking we could consolidate all of the castbar color options into one section in the config [...] Then if someone wanted to use custom colors they only have to make the change once instead of for every unit.

My only concern is that castbar options will be even more spread out since you'd have a color section, and then the individual settings (i.e. show, width, height etc). How about using constants instead? Something like this:

```lua
local CASTBAR_COLOR = {0.9, 0.1, 0.1}
local CASTBAR_INTERRUPT_COLOR = {1, 0, 1}
...
        ["target"] = {
            ...
            castbar = {
                ...
                color = CASTBAR_COLOR,
                interruptColor = CASTBAR_INTERRUPT_COLOR,
```

This way you kind of get both. The actual setting group with the rest of the castbar options (like today), but can change the values centrally.

>match the colors to the default blizzard colors.

Definitely this!

>We can also easily make the castbar show interrupted. It only takes a single line to enable it and then a few more to handle the coloring.

Yeah I think that would probably be useful. I kind if like the approach of a third color when a spell has been successfully interrupted.

>Currently, in your UI, we have red for all target castbars with border coloring for interruptible spells, and we have I think, grey, green and yellow colors for nameplate castbars with again 2 different borders colors.

Honestly, red for interruptible is backwards.

**Comment by Grimsbain** [comment]
>  How about using constants instead? Something like this:
> 
> local CASTBAR_COLOR = {0.9, 0.1, 0.1}
> local CASTBAR_INTERRUPT_COLOR = {1, 0, 1}

That sounds like a good idea.

**Comment by Grimsbain** [comment]
What do you think of this? The castbar uses the same color as the default castbars and colors the border red if you can't interrupt the cast and no coloring if you can. Then if the cast fails it will display interrupted with a red background. 

https://youtu.be/NPERgcAMeHQ

Also here is an example of something that you can't interrupt.

![wowscrnshot_080918_033835](https://user-images.githubusercontent.com/140057/43891930-cf726e2e-9b87-11e8-81da-f7b10e13492c.jpg)

**Comment by Grimsbain** [comment]
We can also have the option of having different color background depending on if the spell is channeled or not. The default Blizzard castbars use yellow for casts and green for channeled spells. Doing this is easy enough the castbar already has the information it needs we would just need a if then check for it when we set the colors.

**Comment by Grimsbain** [comment]
Yeah the class color option for the player castbar is definitely staying in. What did you think about coloring the background for channeled spells and making the fail cast background customizable?

**Comment by lithammer** [comment]
>What did you think about coloring the background for channeled spells and making the fail cast background customizable?

I like it!

**Comment by Grimsbain** [comment]
Took a bit more work than I was expecting since I also made some upgrades to how the bars are colored and updated the boss and arena castbars to use the new system but I think everything should be working now. I did some testing in Ragefire Chasm and didn't have any issues.

![wowscrnshot_080918_073614](https://user-images.githubusercontent.com/140057/43903738-4f518c3e-9baa-11e8-8779-062eba54e0d4.jpg)
![wowscrnshot_080918_073631](https://user-images.githubusercontent.com/140057/43903749-547647f4-9baa-11e8-8223-0d3bab64f8e5.jpg)
